import = [
 "~/.config/alacritty/theme/gruvbox.toml"
]

[window]
decorations = "none"

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 5
y = 0

[keyboard]
bindings = [
  { key = "Key6", mods = "Control", chars = "\u001e" }
]

[font]
size = 25
  [font.normal]
    family = "FiraCode Nerd Font"
    style = "Regular"

  [font.bold]
    family = "FiraCode Nerd Font"
    style = "Bold"

  [font.italic]
    family = "FiraCode Nerd Font"
    style = "Italic"

  [font.bold_italic]
    family = "FiraCode Nerd Font"
    style = "Bold Italic"

