import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font]
size = 42
[font.normal]
    family = "DroidSansMono Nerd Font"
    style = "Regular"

  [font.bold]
    family = "DroidSansMono Nerd Font"
    style = "Bold"

  [font.italic]
    family = "DroidSansMono Nerd Font"
    style = "Italic"

  [font.bold_italic]
    family = "DroidSansMono Nerd Font"
    style = "Bold Italic"

[window]
decorations = "none"

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 5
y = 0

[keyboard]
bindings = [
  { key = "Key6", mods = "Control", chars = "\u001e" }
]

