import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font]
size = 25
[font.normal]
    family = "DroidSansMono Nerd Font"
    style = "Regular"

  [font.bold]
    family = "DroidSansMono Nerd Font"
    style = "Regular"

  [font.italic]
    family = "DroidSansMono Nerd Font"
    style = "Regular"

  [font.bold_italic]
    family = "DroidSansMono Nerd Font"
    style = "Regular"

[window]
decorations = "none"

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 5
y = 0
