return {
  {"prichrd/netrw.nvim"},
  { "folke/noice.nvim", event = "VeryLazy" },
  { "sainnhe/gruvbox-material" },
  { 'nvim-lualine/lualine.nvim' },
  { 'rhysd/git-messenger.vim' },
  { "f-person/git-blame.nvim" },
  { "nvim-treesitter/playground" },
  { "mbbill/undotree" },
  { "theprimeagen/harpoon" },
  { "wakatime/vim-wakatime" },
  { "neovim/nvim-lspconfig" },
  { "neoclide/coc.nvim", branch = "release"},
  { "norcalli/nvim-colorizer.lua" },
  { "windwp/nvim-autopairs", event = "InsertEnter", opts = {}},
  { "terrortylor/nvim-comment" },
  { "MunifTanjim/nui.nvim" },
  { "rcarriga/nvim-notify" },
  { "arthurxavierx/vim-caser" },
  { 'nvim-tree/nvim-web-devicons' },
}

