[cmd_duration]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[c]
disabled = true

[python]
disabled = true

[lua]
disabled = true

[java]
disabled = true

[gradle]
disabled = true

[docker_context]
disabled = true

[vagrant]
disabled = true

[golang]
disabled = true
