#!/bin/bash

stow zshrc
stow tmux
stow config -t ~/.config 
# stow alacritty -t /mnt/c/Users/thoms/AppData/Roaming/alacritty
echo "Unfortunately, you need to manually move the contents from config/alacritty -> Users/thoms/AppData/Roaming/alacritty"
